version: '0.1'

services:
  stats-server:
    image: ${DOCKER_IMAGE:-ghcr.io/lamarquenet/stats-server:latest}
    platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    container_name: stats-server
    restart: unless-stopped
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    volumes:
      - stats_server:/data/
      # mount the new RSA private key read-only
      - /home/aiserver/.ssh/host-trigger-rsa:/root/.ssh/id_rsa:ro
      # known_hosts as before
      - /home/aiserver/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    environment:
      - PORT=${PORT:-8002}
      - RUNNING_IN_DOCKER=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - stats-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

networks:
  stats-network:
    driver: bridge