version: '0.1'

services:
  stats-server:
    image: ${DOCKER_IMAGE:-ghcr.io/lamarquenet/stats-server:latest}
    platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    container_name: stats-server
    restart: unless-stopped
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    environment:
      - PORT=${PORT:-8002}
    networks:
      - stats-network

networks:
  stats-network:
    driver: bridge