version: '0.1'

services:
  stats-server:
    image: ${DOCKER_IMAGE:-ghcr.io/lamarquenet/stats-server:latest}
    platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    container_name: stats-server
    restart: unless-stopped
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    volumes:
      - stats_server:/data/
      - /home/aiserver/.ssh/host-trigger:/root/.ssh/id_ed25519:ro
    environment:
      - PORT=${PORT:-8002}
      - RUNNING_IN_DOCKER=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - stats-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  stats-network:
    driver: bridge